In [1]:
import torch

In [5]:
t1 = torch.tensor(4)
t2 = torch.tensor(4.)
print(t1)
print(t2)

tensor(4)
tensor(4.)


In [6]:
t1.dtype

torch.int64

In [7]:
t2.dtype

torch.float32

In [9]:
t3 = torch.tensor([1.,2,3,4])
t3

tensor([1., 2., 3., 4.])

In [10]:
t3.dtype

torch.float32

In [61]:
#always make sure that you are making dtpye is float, because ML mostly producde float resuts.
t4 = torch.tensor([[1,2],[3,4],[5,6]],dtype=float)
t4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [62]:
#tensor should have same datatype across all the value and it shape should be in the matrix form
t5 = torch.tensor([[[1,2,3],[3,4,5]],[[4,5,6],[4,5,6]]])
t5

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[4, 5, 6],
         [4, 5, 6]]])

In [63]:
t5.shape

torch.Size([2, 2, 3])

In [64]:
t1.shape #as just a value

torch.Size([])

In [65]:
t3.shape

torch.Size([4])

In [66]:
t4.shape

torch.Size([3, 2])

Tensor operations and gradients

In [68]:
x = torch.tensor(3.)

#if we want to take gradient of the parameter then set true
#w,b parameter and x is constant

w = torch.tensor(4. ,requires_grad=True)
b = torch.tensor(5. ,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [69]:
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [70]:
#we can directly calculate the derivative of y with respect to w and b
y.backward()

In [71]:
#display the gradients
print('dy/dx: ', x.grad)
print('dy/dw: ',w.grad)
print('dy/db: ',b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


Torch Functions

In [72]:
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [73]:
#concatenate two tensors with compatible shape
#by defalut dim: is 0
t7 = torch.cat((t4,t6))
t7

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [42., 42.],
        [42., 42.],
        [42., 42.]], dtype=torch.float64)

In [74]:
x = torch.randn(2,3)
x

tensor([[-0.6219,  0.2834,  1.5280],
        [-0.2170, -0.0368, -0.5022]])

In [75]:
torch.cat((x,x,x),dim=0) #row concate

tensor([[-0.6219,  0.2834,  1.5280],
        [-0.2170, -0.0368, -0.5022],
        [-0.6219,  0.2834,  1.5280],
        [-0.2170, -0.0368, -0.5022],
        [-0.6219,  0.2834,  1.5280],
        [-0.2170, -0.0368, -0.5022]])

In [76]:
torch.cat((x,x,x),dim=1) #column concate

tensor([[-0.6219,  0.2834,  1.5280, -0.6219,  0.2834,  1.5280, -0.6219,  0.2834,
          1.5280],
        [-0.2170, -0.0368, -0.5022, -0.2170, -0.0368, -0.5022, -0.2170, -0.0368,
         -0.5022]])

In [77]:
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]], dtype=torch.float64)

In [81]:
t9=t8.reshape(3,2,2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]], dtype=torch.float64)

In [83]:
t10 = t8.reshape(2,2,3)
t10

tensor([[[ 0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794]],

        [[-0.9165, -0.9165, -0.9165],
         [-0.9165, -0.9165, -0.9165]]], dtype=torch.float64)

Numpy and tensor

In [84]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [85]:
#convert numpy to tensor
y = torch.from_numpy(x)
y

tensor([1, 2, 3], dtype=torch.int32)

In [88]:
#convert to numpy
z = y.numpy()
z

array([1, 2, 3])